telegram_bot_token = ""

# telegram ids
admin_ids = ""

# telegram usernames
admin_names = ""

# show participant lists to all participants
public_lists = false

# days to keep users in the black list
black_list_time = 30