[package]
name = "event-manager-telegram-bot"
version = "0.0.1"
authors = ["vadim.frolov@thank-u.org"]
edition = "2021"

[[bin]]
name = "event-manager-telegram-bot"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.47"
serde = { version = "1.0", features = [ "derive" ] }
serde_json = { version = "1.0.73", features = [ "preserve_order" ] }
clap = "~2.33"
toml = "0.5.8"
lru = "0.7.6"
futures = "0.3"
telegram-bot = { git = "https://github.com/telegram-rs/telegram-bot"}
log = "0.4"
env_logger = "0.9.0"
tokio = { version =  "1.8", features = ["rt-multi-thread", "macros"] }
fallible-streaming-iterator = "0.1.9"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.rusqlite]
version = "0.27.0"
features = ["bundled"]
