---
- hosts: "docker_compose"
  gather_facts: yes
  become: true
  tasks:
    - name: Generate config file for current version
      template:
        src: event-manager-telegram-bot.toml.j2
        dest: "/usr/local/etc/event-manager-telegram-bot.{{ docker_image_version }}.toml"

    - name: Create dir
      file:
        path: "/opt/{{ docker_image_version }}/data"
        state: directory
        recurse: yes
        owner: docker
        group: docker

    - name: Generate docker-compose file for current version
      template:
        src: docker-compose.yml.j2
        dest: "/opt/{{ docker_image_version }}/docker-compose.{{ docker_image_version }}.yml"

    - name: Authorize docker-compose
      shell: |
        docker login -u ${{ github_actor }} -p ${{ PAT_TOKEN }} ${{ github_registry }}
        docker-compose -f /opt/{{ docker_image_version }}/docker-compose.{{ docker_image_version }}.yml pull

    - name: Restart docker-compose for current version
      docker_compose:
        project_src: "/opt/{{ docker_image_version }}"
        state: present
        recreate: always
        pull: yes
        remove_orphans: yes
        files:
          - "docker-compose.{{ docker_image_version }}.yml"