---
- hosts: "docker_compose"
  gather_facts: yes
  become: true
  tasks:
    - name: Generate config file for current version
      template:
        src: event-manager-telegram-bot.toml.j2
        dest: "/usr/local/etc/event-manager-telegram-bot.{{ docker_image_version }}.toml"

    - name: Create group docker
      group:
        name: docker
        state: present

    - name: Create user docker
      user:
        name: docker
        group: docker
        shell: /bin/bash
        createhome: yes
        state: present
        id: 1001

    - name: Create dir
      file:
        path: "/opt/{{ docker_image_version }}/data"
        state: directory
        recurse: yes
        owner: docker
        group: docker

    - name: Generate docker-compose file for current version
      template:
        src: docker-compose.yml.j2
        dest: "/opt/{{ docker_image_version }}/docker-compose.{{ docker_image_version }}.yml"

    - name: Restart docker-compose for current version
      docker_compose:
        project_src: "/opt/{{ docker_image_version }}"
        state: present
        recreate: always
        pull: yes
        remove_orphans: yes
        files:
          - "docker-compose.{{ docker_image_version }}.yml"