name: Build and deploy container

on:
  push:
    branches:
      - "prerelease"
      - "main"
    paths:
      - 'Dockerfile'
      - '.github/workflows/build_and_deploy_container.yml'
  workflow_run:
    workflows:
      - Rust build and create Release
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-deploy-container:
    environment: ${{ github.base_ref }}
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      - name: Get Latest Release
        id: get_latest_release
        uses: pozetroninc/github-action-get-latest-release@v0.7.0

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            "REPOSITORY_ADDRESS=${{ github.server_url }}/${{ github.repository }}"
            "RELEASE_VERSION=${{ steps.binary_version.outputs.binary_version_tag }}"