name: Lint and test

on: [ push ]

jobs:
  run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Rust
        command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      - name: Install Rustfmt
        run: rustup component add rustfmt
      - name: Run Rustfmt
        run: cargo fmt --all -- --check
      - uses: actions-rs/cargo@v1.0.1
        with:
          command: test

