name: Prepary host

on:
  push:
    branches:
      - "prerelease"
      - "main"
    paths:
      - 'iaac/ansible/inventory/**'
      - 'iaac/ansible/playbooks/prepare_hosts.yml'
      - 'iaac/ansible/roles/requirements.yml'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  prepare-hosts:
    environment: ${{ github.base_ref }}
    runs-on: ubuntu-20.04
    permissions: write-all

    steps:
      - name: Install docker and docker-compose on target instance
        run: |
          ansible-galaxy install -r iaac/ansible/roles/requirements.yml
          eval "$(ssh-agent -s)"
          echo -n ${{ secrets.DEPLOY_SSH_KEY }} | base64 -d | ssh-add -
          ansible-playbook --user ${{ secrets.DEPLOY_SSH_USER }} -i iaac/ansible/inventory \
          iaac/ansible/playbooks/docker-compose.yml --extra-vars "\
          target_host=\"${{ secrets.DOCKER_HOST_ADDRESS }}\" \
          ansible_sudo_pass=\"${{ secrets.DEPLOY_USER_PASSWORD }}\" \
          docker_compose_install_fq_link=\"/usr/bin/docker-compose\" \
          docker_image_version=\"${{ steps.meta.outputs.version }}\" \
          TELEGRAM_BOT_TOKEN=\"${{ secrets.TELEGRAM_BOT_TOKEN }}\" \
          PAYMENT_PROVIDER_TOKEN=\"${{ secrets.PAYMENT_PROVIDER_TOKEN }}\"
          telegram_admin_ids_list=\"${{ vars.TELEGRAM_ADMIN_IDS_LIST }}\""